version: '3.8'
services:
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    container_name: dynamodb-local
    restart: unless-stopped
    ports:
      - "8000:8000"
    user: root
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  bot:
    image: golang:1.22-bookworm
    container_name: anonymous-bot
    working_dir: /app
    volumes:
      - ./bot:/app
      - go-mod-cache:/go/pkg/mod
    command: go run localwrapper.go
    ports:
      - "8080:8080"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}

volumes:
  dynamodb-data:
  go-mod-cache: